### ISSUE TITLE
Null pointer exception while checking syntax

### ISSUE THREAD

**Issue by magoorden** [UPPAALModelChecker/UPPAAL-Meta#163]
**Describe the bug**
During a live modeling session today I encountered the following exception while checking the syntax of the model. Now at the end of the session I don't know exactly which feature of the model caused this error, so I don't have a minimal working example unfortunately.

```
java.lang.NullPointerException: Cannot invoke "String.trim()" because the return value of "com.uppaal.model.core2.Node.getPropertyValue(String)" is null
	at com.uppaal.model.system.UppaalSystem.findNode(UppaalSystem.java:64)
	at com.uppaal.model.system.UppaalSystem.findTemplate(UppaalSystem.java:72)
	at com.uppaal.model.system.UppaalSystem.addProcess(UppaalSystem.java:91)
	at com.uppaal.engine.protocol.JsonProtocol.produceSystem(JsonProtocol.java:230)
	at com.uppaal.engine.protocol.JsonProtocol.upload(JsonProtocol.java:217)
	at com.uppaal.engine.EngineStub.upload(EngineStub.java:448)
	at com.uppaal.engine.Engine$7.run(Engine.java:384)
	at com.uppaal.engine.Engine.lambda$submitLicenseLess$1(Engine.java:764)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**To Reproduce**
Do live modeling for a group and check the syntax.

**Expected behavior**
The error message should explain to the modeler what the problem is.

**Version(s) of UPPAAL tested**
Stratego 10

**Desktop (please complete the following information):**
Version: UPPAAL 4.1.20-stratego-10 (rev. 37ECAAA437FE60EE), October 2022
OS, Java version: macOS 12.6.1

**Comment by mikucionisaau** [comment]
The provided stacktrace has enough information, thank you for the report!
