### ISSUE TITLE
`StringIndexOutOfBoundsException` with UPPAAL 4.1.26-1 

### ISSUE THREAD

**Issue by siiky** [UPPAALModelChecker/UPPAAL-Meta#203]
**Describe the bug**
When trying to start UPPAAL from the terminal, I get a `StringIndexOutOfBoundsException` error:

```
Exception in thread "main" java.lang.ExceptionInInitializerError
Caused by: java.lang.StringIndexOutOfBoundsException: Range [0, -1) out of bounds for length 5
	at java.base/jdk.internal.util.Preconditions$1.apply(Preconditions.java:55)
	at java.base/jdk.internal.util.Preconditions$1.apply(Preconditions.java:52)
	at java.base/jdk.internal.util.Preconditions$4.apply(Preconditions.java:213)
	at java.base/jdk.internal.util.Preconditions$4.apply(Preconditions.java:210)
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:98)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckFromToIndex(Preconditions.java:112)
	at java.base/jdk.internal.util.Preconditions.checkFromToIndex(Preconditions.java:349)
	at java.base/java.lang.String.checkBoundsBeginEnd(String.java:4608)
	at java.base/java.lang.String.substring(String.java:2720)
	at com.uppaal.gui.Main.<clinit>(Unknown Source)
```

**To Reproduce**
```sh
./uppaal
# OR
java -jar uppaal.jar
```

**Expected behavior**
The UPPAAL GUI appears.

**Version(s) of UPPAAL tested**
`uppaal64-4.1.26-1`

**Desktop (please complete the following information):**
```
$ java --version
openjdk 21-ea 2023-09-19
OpenJDK Runtime Environment (build 21-ea+7-Debian-1)
OpenJDK 64-Bit Server VM (build 21-ea+7-Debian-1, mixed mode, sharing)

$ bin-Linux/verifyta --version
(Academic) UPPAAL 4.1.26-1 (rev. 7BCF30B7363A9518), February 2022
Copyright (c) 1995 - 2022, Uppsala University and Aalborg University.
All rights reserved.
Compiled with g++-10 -Wall -Wempty-body -DNDEBUG -O3 -ffloat-store -fPIC -mtune=generic -DLIBXML_STATIC -DENABLE_PROB -DENABLE_BRANCHING -DENABLE_BRANCHING -DENABLE_LSC -DENABLE_64BIT -DLOCSTORE  -DBOOST_DISABLE_THREADS -Wsuggest-override
Free for academic and non-commercial use only.

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 12 (bookworm)
Release:	12
Codename:	bookworm

$ uname -r
6.1.0-9-amd64
```

I'm using DWM as the window manager. I've had problems with other Java GUIs in the past, but not with UPPAAL (see next).

**Additional context**
I used UPPAAL last year for a class, everything worked well. I saved the zip file from last year and unzip it just now because I wanted to use it for another project. OS packages, &c have been updated in the meantime, but could that really be it?

**Comment by mikucionisaau** [comment]
Thanks for the nice report. 
I suspect that openjdk changed something about `String` handling again.
Could you please try with OpenJDK-17?

**Comment by siiky** [comment]
On another computer with `openjdk 17.0.6 2023-01-17` (not sure why I have different OpenJDK versions, both PCs have basically the same OS) I got this error dialogue:

![image](https://github.com/UPPAALModelChecker/UPPAAL-Meta/assets/12852780/c25a6dec-8e1b-4740-bde2-5e2902d0aedc)

After clicking OK UPPAAL opens up. When I open a file it shows this error dialogue:

![image](https://github.com/UPPAALModelChecker/UPPAAL-Meta/assets/12852780/86997f79-1993-4f77-a63d-954c07b17b49)

If I go to the verifier I get that same error dialogue again, and a license dialogue. I can't find the license anymore (must have deleted from my email) so I can't try it further (and I ended up not needing UPPAAL to disprove what I wanted).

Let me know if there's anything else you'd like me to test without a license.

**Comment by mikucionisaau** [comment]
That other computer probably uses an older `libc` and thus the engine is crashing, which is unrelated to the OpenJDK issue.

**Comment by mikucionisaau** [comment]
Also you need to fix your desktop font configuration, for some reason Java is not getting correct settings... Probably the easiest is to add the following to you `~/.Xresources`:
```
Xft.antialias:          1
Xft.hinting:            1
Xft.rgba:               none
Xft.hintstyle:          hintfull
```

Could you try uppaal-5 release instead?
