### ISSUE TITLE
license activation return error 422 when computer name includes unicode characters

### ISSUE THREAD

**Issue by wwwwwwwwwwwwwwwwwwwwwwwwwwwwww2** [UPPAALModelChecker/UPPAAL-Meta#225]
**Describe the bug**
The bug will occur when you try to verify the licience on a computer with japanese device name

**To Reproduce**
1. Go to Setting ->System->Version
2. Click on 'Change PC name'
3. Change it to including whatever japanese symbol (in my case,  the device name was あおいのG1619-03) 
4. See error -> you should get an error "ERROR 422 missing device"

error log included below

    com.uppaal.engine.EngineCrashException: Error 422: missing device
	at com.uppaal.engine.protocol.FragileResponse.validate(FragileResponse.java:21)
	at com.uppaal.engine.protocol.JsonMessageParser.parse(JsonMessageParser.java:73)
	at com.uppaal.engine.protocol.JsonMessageParser.parse(JsonMessageParser.java:42)
	at com.uppaal.engine.protocol.JsonProtocol.getBasicResponse(JsonProtocol.java:461)
	at com.uppaal.engine.protocol.JsonProtocol.getLeaseRequest(JsonProtocol.java:612)
	at com.uppaal.engine.EngineStub.getLeaseRequest(EngineStub.java:598)
	at com.uppaal.engine.Engine.lambda$getLeaseRequest$10(Engine.java:734)
	at com.uppaal.engine.Engine.lambda$submit$8(Engine.java:654)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1589)

    Caused by: com.uppaal.engine.EngineInvocationException: Concurrent execution encountered an exception
	at com.uppaal.engine.Engine.submit(Engine.java:647)
	at com.uppaal.engine.Engine.submitLicenseLess(Engine.java:637)
	at com.uppaal.engine.Engine.getLeaseRequest(Engine.java:733)
	at aq.n(Unknown Source)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Expected behavior**
The system should be able verify the licience without issue, even without changing the device name to pure english character just for this programme

**Version(s) of UPPAAL tested**
A list of UPPAAL versions where the behaviour is observed, and optionally a version where it works as expected. 
[Windows version 5.0.0]
[Windows version 5.1.0]

**Desktop (please complete the following information):**
 - Version [5.0.0]
 - OS, Java version: [Windows 11 64bit, Java 17]

**Additional context**
As it magically solved after i removed the japanese character in the device name,  and happened again after i add back those characters, i don't really sure if that is a single case or a common problem.

**Comment by mikucionisaau** [comment]
This has been addressed in 5.1.0-beta4 (and partly by 5.1.0-beta3).
UPPAAL should work with unicode symbols in computer name and username (used to store the lease in the path composed with these elements).

Feel free to reopen if the issue persists.
