### ISSUE TITLE
JVM Installed but Warning Appears

### ISSUE THREAD

**Issue by rgu01** [UPPAALModelChecker/UPPAAL-Meta#42]
**Describe the bug**
UPPAAL 4.1.24 (rev. 29A3ECA4E5FB0808) and UPPAAL 4.1.20-stratego-7 (rev. 12D93ED5FE521036), clicking the uppaal.exe shows:

![image](https://user-images.githubusercontent.com/39125216/126961522-f1274586-d9ca-4834-a7ad-394d85fbfa5d.png)

However, when running: java -jar uppaal.jar in the command line, they start correctly.

In addition, running UPPAAL65-4.1.25-5 in the command line: java -jar uppaal.jar, it shows:

_Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/uppaal/gui/Main has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:601)_

**Version(s) of UPPAAL tested**
(Academic) UPPAAL 4.1.24 (rev. 29A3ECA4E5FB0808), November 2019
(Academic) UPPAAL 4.1.20-stratego-7 (rev. 12D93ED5FE521036), December 2019
(Academic) UPPAAL 4.1.25-5 (rev. 643E9477AA51E17F), April 2021

**Desktop (please complete the following information):**
 - My OS: Edition	Windows 10 Education
Version	21H1
Installed on	‎1/‎13/‎2021
OS build	19043.1052
Experience	Windows Feature Experience Pack 120.2212.2020.0

 - My version of JAVA:
openjdk version "1.8.0_292"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_292-b10)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.292-b10, mixed mode)

**Comment by yrke** [comment]
From the message it seems UPPAAL64-4.1.25-5 requires Java 11, and that the generated EXE files fails to pick this up.
This will be fixed in upcoming versions of UPPAAL. For now you can use Java 11.
