### ISSUE TITLE
Internal error when all templates are removed

### ISSUE THREAD

**Issue by magoorden** [UPPAALModelChecker/UPPAAL-Meta#72]
**Describe the bug**
When all templates are removed, an internal error is thrown (see below). The error is triggered when you click on `Declarations`. Clicking on `System declarations` if fine though.

```
java.lang.ClassCastException: class com.uppaal.model.core2.QueryList cannot be cast to class com.uppaal.model.core2.AbstractTemplate (com.uppaal.model.core2.QueryList and com.uppaal.model.core2.AbstractTemplate are in unnamed module of loader 'app')
	at com.uppaal.model.core2.Document.getTemplates(Document.java:205)
	at em.a(Unknown Source)
	at java.desktop/java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:341)
	at java.desktop/java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:333)
	at java.desktop/java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:266)
	at jY.a(Unknown Source)
	at hE.a(Unknown Source)
	at java.desktop/javax.swing.JTree.fireValueChanged(JTree.java:2967)
	at java.desktop/javax.swing.JTree$TreeSelectionRedirector.valueChanged(JTree.java:3456)
	at java.desktop/javax.swing.tree.DefaultTreeSelectionModel.fireValueChanged(DefaultTreeSelectionModel.java:641)
	at java.desktop/javax.swing.tree.DefaultTreeSelectionModel.notifyPathChange(DefaultTreeSelectionModel.java:1111)
	at java.desktop/javax.swing.tree.DefaultTreeSelectionModel.setSelectionPaths(DefaultTreeSelectionModel.java:297)
	at java.desktop/javax.swing.tree.DefaultTreeSelectionModel.setSelectionPath(DefaultTreeSelectionModel.java:191)
	at java.desktop/javax.swing.JTree.setSelectionPath(JTree.java:1656)
	at java.desktop/javax.swing.plaf.basic.BasicTreeUI.selectPathForEvent(BasicTreeUI.java:2736)
	at java.desktop/javax.swing.plaf.basic.BasicTreeUI$Handler.handleSelection(BasicTreeUI.java:4016)
	at java.desktop/javax.swing.plaf.basic.BasicTreeUI$Handler.mousePressedDND(BasicTreeUI.java:3993)
	at java.desktop/javax.swing.plaf.basic.BasicTreeUI$Handler.mousePressed(BasicTreeUI.java:3952)
	at java.desktop/java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:287)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6632)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
	at java.desktop/java.awt.Component.processEvent(Component.java:6400)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5011)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4843)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4544)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2772)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4843)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**To Reproduce**
1. Create a new model.
2. Right click on `Template` and select `Remove template`.
3. Click `Declarations`.
4. See error.

**Expected behavior**
I was expecting no error.

**Version(s) of UPPAAL tested**
Uppaal Stratego 9.

**Desktop (please complete the following information):**
 - Version UPPAAL 4.1.20-stratego-9 (rev. 67D95DBCE6B8B4ED), January 2022
 - OS, Java version: Ubuntu 20.04.3 LTS

**Comment by magoorden** [comment]
This error can also observed when you want to add a template once all have been removed. For this, do the following:

1. Create a new model.
2. Right click on `Template` and select `Remove template`.
3. Go to `Edit` -> `Insert template`.
4. See error.

**Comment by mikucionisaau** [comment]
The last template can no longer be removed in Stratego-10
![image](https://user-images.githubusercontent.com/4868894/194233449-b22b779a-d4c4-4970-8c4c-bb5b93402665.png)

**Comment by magoorden** [comment]
Preventing the last template to be removed didn't solve this internal error in all cases. Today I (just) let ChatGPT generate an Uppaal model for me (but imagine that ChatGPT is replace by another external tool that can generate Uppaal models), but this one didn't have any templates in the generated xml-file. Opening that one caused to trigger this error again.

To summarize, the currently implemented solution prevents invalid models to be created if the user uses the Uppaal GUI for editing, but doesn't solve the problem in general.

**Comment by mikucionisaau** [comment]
Confirmed on Uppaal-5
Open the model where templates are absent and click on declarations.
```
java.lang.ClassCastException: class com.uppaal.model.core2.QueryList cannot be cast to class com.uppaal.model.core2.AbstractTemplate (com.uppaal.model.core2.QueryList and com.uppaal.model.core2.AbstractTemplate are in unnamed module of loader 'app')
	at com.uppaal.model.core2.Document.getTemplates(Document.java:201)
	at fq.a(Unknown Source)
```
